apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akscalexkau-4b4a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akscalexkau-4b4a"
  template:
    metadata:
      labels:
        app: "akscalexkau-4b4a"
    spec:
      containers:
        - name: "akscalexkau-4b4a"
          image: "akscoursealexkau.azurecr.io/akscalexkau"
          ports:
          - containerPort: 80